### ISSUE TITLE
An error occurred while installing RedCloth (4.2.9), and Bundler cannot continue.

### ISSUE THREAD

**Issue by feeloc** [gitlabhq/gitlab-recipes#239]
When I do
`sudo -u git -H bundle install --deployment --without development test postgres aws`
output

```
An error occurred while installing RedCloth (4.2.9), and Bundler cannot
continue.
Make sure that `gem install RedCloth -v '4.2.9'` succeeds before bundling.
```

I run `gem install RedCloth -v '4.2.9`, successed.  But the err also show!!

Who can help me,  thx!!

**Comment by odigity** [comment]
I just experienced this error when trying to install a new omniauth gem in the gitlab/gitlab-ce docker container.  I have not installed any additional rubies, or done anything significant before editing `/opt/gitlab/embedded/service/gitlab-rails/Gemfile` and running `bundle install` in that dir.

I tried:

    bundle install --without development test mysql --path vendor/bundle --no-deployment
    bundle install --without development test mysql --system --no-deployment

Both times it failed on RedCloth.

**Comment by ayufan** [comment]
@odigity Why do you want to install a new gem?

**Comment by odigity** [comment]
@ayufan Because I need to add another omniauth provider.

**Comment by gopikrishnakolla** [comment]
@odigity If it is ubuntu, try installing cmake, pkg-config, build-essential using apt-get and then retry.

**Comment by nishant-n** [comment]
@gopikrishnakolla installed cmake, pkg-config, build-essential but still not working on ubuntu 14.04

**Comment by Ddper** [comment]
@feeloc 
u install  RedCloth in root user，so the bin directory was created by root

Gem::FilePermissionError: You don't have write permissions for the /home/git/gitlab/vendor/bundle/ruby/2.1.0/bin directory.

execute: chown -R git:git /home/git/gitlab/vendor/bundle/ruby/2.1.0/bin

problem solved.

**Comment by manasvigupta** [comment]
I was able to resolve this issue by following comments on S[tackoverflow thread](https://stackoverflow.com/questions/12119138/failed-to-build-gem-native-extension-when-install-redcloth-4-2-9-install-linux)

Specifically,  fixed by executing following command first.

`sudo apt-get install ruby-dev`
