### ISSUE TITLE
Apache GitLab Configuration

### ISSUE THREAD

**Issue by AidanMontare** [gitlabhq/gitlab-recipes#243]
I recently decided to install GitLab on my web server (already running a small personal website) to host my projects. Since the server was already using Apache, I decided to attempt to configure GitLab to use Apache.

The install went uneventfully, and using the I now have the following setup:
- My server (Ubuntu 14.04 LTS)
- Apache (2.4)
- Gitlab 7.4.3 installed from the omnibus at https://about.gitlab.com/downloads/

GitLab has the following in /etc/gitlab/gitlab.rb:

```
nginx['enable'] = false
web_server['external_users'] = ['www-data']
```

My Apache configuration is based off https://gitlab.com/gitlab-org/gitlab-recipes/blob/master/web-server/apache/gitlab-ssl-apache2.4.conf, and looks like this (stuff unrelated to the issue removed):

```
<VirtualHost *:80>
        ServerName code.aidanmontare.net
        Redirect permanent / https://code.aidanmontare.net/
</VirtualHost>
<IfModule mod_ssl.c>
        <VirtualHost *:443>
                # Host Information
                ServerName code.aidanmontare.net

                ProxyPreserveHost On
                ProxyTimeout 5
                ProxyRequests Off

                # Ensure that encoded slashes are not decoded but left in their encoded state.
                # http://doc.gitlab.com/ce/api/projects.html#get-single-project
                AllowEncodedSlashes NoDecode

                <Location />
                        # New authorization commands for apache 2.4 and up
                        # http://httpd.apache.org/docs/2.4/upgrading.html#access
                        Require all granted
                        ProxyPassReverse http://127.0.0.1:8080
                        ProxyPassReverse https://code.aidanmontare.net/
                </Location>

                #apache equivalent of nginx try files
                # http://serverfault.com/questions/290784/what-is-apaches-equivalent-of-nginxs-try-files
                # http://stackoverflow.com/questions/10954516/apache2-proxypass-for-rails-app-gitlab
                RewriteEngine on
                RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} !-f
                RewriteRule .* http://127.0.0.1:8080%{REQUEST_URI} [P,QSA]
                RequestHeader set X_FORWARDED_PROTO 'https'

                # needed for downloading attachments
                # This is where GitLab omnibus (package installer) put them
                DocumentRoot /var/opt/gitlab/gitlab-rails/

                #Set up apache error documents, if back end goes down (i.e. 503 error) then a maintenance/deploy page is thrown up.
                ErrorDocument 404 /404.html
                ErrorDocument 422 /422.html
                ErrorDocument 500 /500.html
                ErrorDocument 503 /deploy.html
        </VirtualHost>
</IfModule> 
```

Once I sorted out some certificate issues I was having, I can now use the GitLab web interface. Browsing around a preforming basic tasks mostly works.

However, I tried adding a test repository and recieved the following error upon clicking "add project":

```
422
The change you wanted was rejected.

Maybe you tried to change something you didn't have access to.
```

Also, GitLab runs painfully slowly (as compared to a test installation VM on my local computer using the included Nginx). Using the Firefox network monitor, I see that one resource is generating 502 errors like the following:

```
Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /assets/application-d78e3aebfdf9aa068bc71234b2bfea02.js.

Reason: Error reading from remote server
```

Also, in my Apache log I see many entries like the following:

```
[X] [proxy_http:error] [pid 16705] (20014)Internal error: [client X] AH01102: error reading status line from remote server 127.0.0.1:8080
[X] [proxy:error] [pid 16705] [client X] AH00898: Error reading from remote server returned by /assets/application-d78e3aebfdf9aa068bc71234b2bfea02.js
```

This same resource seems to be a problem for every page I load.

Any thoughts? I have tried a lot of ideas I saw around the web relating to these problems, and none so far have seemed to work.

**Comment by Braunson** [comment]
Any updates on the sluggishness? I'm running CentOS6 with GitLab 7.7.2 Omnibus 5.4.2 on Apache 2.2 and well over a two minutes to load any page..

**Comment by AidanMontare** [comment]
I'm on 2.4 and Ubuntu Server, and things seem to be running quite well now, though I have logs enabled and such. Some pages still take some time to load, but I haven't ran into any that timeout like they used to. I'm actually not quite sure what it is that made it work better.

**Comment by dsoap** [comment]
I have set-up gitlab to run on my current Apache web server yet when I go to my URL I get a screen that says; Not Found: /   And when I try to access anything in the public folder I can have it show up on the browser screen such as the deply.html screen. How do I get this to allow me to access to the main log in page?
