### ISSUE TITLE
Bitbucket import: Undefined method 'gitlab_key'

### ISSUE THREAD

**Issue by R3dy** [gitlabhq/gitlab-recipes#252]
When trying this script I receive the following error.

<pre>
enterprise:bitbucket rdavis$ ./bitbucket2gitlab.rb
./bitbucket2gitlab.rb:14:in `<main>': undefined method `gitlab_key' for main:Object (NoMethodError)
enterprise:bitbucket rdavis$
</pre>

I have copied the db-1.0.json file over correctly from my bitbucket export.
<pre>
enterprise:bitbucket rdavis$ ls
LICENSE             README.md           bitbucket2gitlab.rb db-1.0.json
enterprise:bitbucket rdavis$
</pre>

I have renamed all the variables accordingly.  As far as I can tell, Ruby has no clue where the 'gitlab_key' method is defined and I can't seem to locate which library has the definition so I can include it in this script.

surely you knew this when you wrote this so I'm guessing there is something stupid I am missing.  Am I supposed to run this from a certain directory?

Thank you

**Comment by axilleas** [comment]
The method `gitlab_key` is in https://github.com/gitlabhq/gitlab-recipes/blob/master/import/bitbucket/bitbucket2gitlab.rb#L55

All it does is to extract the token from the API. You can just use 
```
@token=your_token_here
```

and omit the usage of this method. You API token can be found in `/profile/account` of your GitLab instance.

**Comment by panaali** [comment]
@R3dy  I had this issue.
I think it should be a problem of ruby version , 
I fix it with this trick : 
"move all `def`  after require `net/http` , the last line should be : `import(load_bitbucket())`


```ruby
#!/usr/bin/env ruby

require 'json'
require 'net/http'

################################################################
## Modify the following global variables to match yout setup. ##
################################################################
## GitLab host without the 'http(s)://' prefix. This is your FQDN.
@host="host"
@base_url="https://#{@host}/"

## Add your credentials here
@token=gitlab_key('user','password')

## Note the %2F to separate namespace and project.
## For example if your project will be named https://example.com/foo/bar,
## replace below with 'foo%2Fbar'.
@project='namespace%2Fproject'

## Change to 80 if you are not going to use ssl (although you should).
@http = Net::HTTP.new("#{@host}",443)

## Set to false if you are not going to use ssl (although you should).
@http.use_ssl=true

#########################
## Kick off the import ##
#########################

import(load_bitbucket())

def load_bitbucket()
  JSON.parse(IO.read('db-1.0.json'))
end

def import(bitbucket_json)
  id_map={}
  bitbucket_json['issues'].each do |issue|
    issue_id=issue['id']
    gitlab_id=post_issue(issue['title'],issue['content'])
    id_map[issue_id]=gitlab_id
    if('resolved' == issue['status'])
      close_issue(gitlab_id)
    end
  end
  bitbucket_json['comments'].each do |comment|
    if comment['content']
      post_comment(id_map[comment['issue']],"#{comment['content']}\n\n#{comment['user']} - #{comment['created_on']}")
    end
  end

end

def gitlab_key(email,password)
  uri = URI("#{@base_url}/api/v3/session")
  res = Net::HTTP.post_form(uri, 'email' => email, 'password' => password)
  JSON.parse(res.body)['private_token']
end

def post_issue(title,description)
  uri = URI("#{@base_url}/api/v3/projects/#{@project}/issues")
  res = Net::HTTP.post_form(uri, 'title' => title, 'description' => description, 'private_token' => @token, 'labels' => ['bitbucket2gitlab'])
  created=JSON.parse(res.body)
  puts created.to_json
  created['id']
end

def post_comment(id,content)
  uri = URI("#{@base_url}/api/v3/projects/#{@project}/issues/#{id}/notes")
  res = Net::HTTP.post_form(uri, 'body' => content,'private_token' => @token)
  created=JSON.parse(res.body)
  puts created.to_json
end

def close_issue(id)

  # uri = URI("#{@base_url}/api/v3/projects/#{@project}/issues")

  request = Net::HTTP::Put.new("/api/v3/projects/#{@project}/issues/#{id}")

  request.set_form_data({'private_token' => @token,'state_event'=>'close'})
  response=@http.request(request)
  puts response.inspect
  puts response.body
end

def get_issues()
  request = Net::HTTP::Get.new("/api/v3/projects/#{@project}/issues?private_token=#{@token}")
  response=@http.request(request)
  puts response.inspect
  puts response.body
end
```

**Comment by stffndtz** [comment]
Thanks to @panaali - as a ruby newbie I was completely lost

**Comment by axilleas** [comment]
The script is deprecated, we can now import right from within GitLab. Closing this.

**Comment by ernstki** [comment]
@axilleas Except when you can't. I get a 5xx error when I try to authorize GitLab to access my Bitbucket account, and it's likely due to restrictive security policies on our internal network over which I have no authority (such as an outbound HTTP proxy which requires authentication); thus I don't think it's worth filing an issue against GitLab itself.

After trying a number of different configuration settings to get GitLab to use our HTTP proxy server, the last option I'm willing to try is to get this script working.

If something productive comes of that, I'll file a PR to resuscitate this script for people who still need it.
