### ISSUE TITLE
Github import > Issue comments ?

### ISSUE THREAD

**Issue by ebuildy** [gitlabhq/gitlab-recipes#254]
Hello,

Thanks for the script, I am wondering if it's possible to import issues comments via the API http://doc.gitlab.com/ce/api/notes.html ? 

And also, do you have any idea how to import and "map" users?

Regards,
Thomas Decaux

**Comment by axilleas** [comment]
Right now it is not possible to import comments. GitLab supports importing GitHub repos via its interface now, so this script should be deprecated.

**Comment by axilleas** [comment]
The script is deprecated, we can now import right from within GitLab. Closing this.
