### ISSUE TITLE
Apache conf file for gitlab ci .

### ISSUE THREAD

**Issue by pavankumarkatakam** [gitlabhq/gitlab-recipes#264]
I have installed gitlab in my loacl server and configured to use apache2  and file https://github.com/gitlabhq/gitlab-recipes/blob/master/web-server/apache/gitlab-apache2.4.conf , but when i opening my gitlab continues integrations url it directly going to apache page but  not the actual page as expected. i think for ci also there should be a apache2 conf file. please provide that anybody. sorry if im worng and correct me please

**Comment by axilleas** [comment]
Closing as GitLab CI is now integrated with GitLab, hence there is no need for a separate config :)
