### ISSUE TITLE
Wrong Issue number?

### ISSUE THREAD

**Issue by NiklasMerz** [gitlabhq/gitlab-recipes#265]
Is it possible that issues get a wrong number?
I looks like it counts backwards or something.

**Comment by NiklasMerz** [comment]
The counter is exactly the oposite

**Comment by axilleas** [comment]
Please report this in https://github.com/gitlabhq/gitlabhq/issues and provide some useful output as written here https://github.com/gitlabhq/gitlabhq/blob/master/CONTRIBUTING.md#issue-tracker-guidelines
