### ISSUE TITLE
how to configure nginx to service GitLab?

### ISSUE THREAD

**Issue by tmacjx** [gitlabhq/gitlab-recipes#274]
hi,guys!I have some problem.
I have learn to  install GitLab Step by step according to the tutorial.
But when I run "nginx -t" command ,there are some issue below this line as you see.
```
nginx: [emerg] BIO_new_file("/etc/nginx/ssl/gitlab.crt") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/nginx/ssl/gitlab.crt','r') error:2006D080:BIO routines:BIO_new_file:no such file)
nginx: configuration file /etc/nginx/nginx.conf test failed
```
Can anyone help me?Thanks a lot.

**Comment by tmacjx** [comment]
Checking Environment ...

Git configured for git user? ... yes

Checking Environment ... Finished

Checking GitLab Shell ...

GitLab Shell version >= 2.0.1 ? ... OK (2.1.0)
Repo base directory exists? ... yes
Repo base directory is a symlink? ... no
Repo base owned by git:git? ... yes
Repo base access is drwxrws---? ... no
  Try fixing it:
  sudo chmod -R ug+rwX,o-rwx /home/git/repositories/
  sudo chmod -R ug-s /home/git/repositories/
  find /home/git/repositories/ -type d -print0 | sudo xargs -0 chmod g+s
  For more information see:
  doc/install/installation.md in section "GitLab Shell"
  Please fix the error above and rerun the checks.
Satellites access is drwxr-x---? ... yes
hooks directories in repos are links: ... can't check, you have no projects
Running /home/git/gitlab-shell/bin/check
Check GitLab API access: /home/git/gitlab-shell/lib/gitlab_net.rb:122:in `read': No such file or directory - /home/git/gitlab-shell/.gitlab_shell_secret (Errno::ENOENT)
	from /home/git/gitlab-shell/lib/gitlab_net.rb:122:in `secret_token'
	from /home/git/gitlab-shell/lib/gitlab_net.rb:79:in `get'
	from /home/git/gitlab-shell/lib/gitlab_net.rb:39:in `check'
	from /home/git/gitlab-shell/bin/check:11:in `<main>'
gitlab-shell self-check failed
  Try fixing it:
  Make sure GitLab is running;
  Check the gitlab-shell configuration file:
  sudo -u git -H editor /home/git/gitlab-shell/config.yml
  Please fix the error above and rerun the checks.

Checking GitLab Shell ... Finished

Checking Sidekiq ...

Running? ... yes
Number of Sidekiq processes ... 1

Checking Sidekiq ... Finished

Checking LDAP ...

LDAP is disabled in config/gitlab.yml

Checking LDAP ... Finished

Checking GitLab ...

Database config exists? ... yes
Database is SQLite ... no
All migrations up? ... yes
Database contains orphaned GroupMembers? ... no
GitLab config exists? ... yes
GitLab config outdated? ... no
Log directory writable? ... yes
Tmp directory writable? ... yes
Init script exists? ... yes
Init script up-to-date? ... no
  Try fixing it:
  Redownload the init script
  For more information see:
  doc/install/installation.md in section "Install Init Script"
  Please fix the error above and rerun the checks.
projects have namespace: ... can't check, you have no projects
Projects have satellites? ... can't check, you have no projects
Redis version >= 2.0.0? ... yes
Ruby version >= 2.0.0 ? ... yes (2.0.0)
Your git bin path is "/usr/bin/git"
Git version >= 1.7.10 ? ... yes (1.8.3)

Checking GitLab ... Finished

**Comment by axilleas** [comment]
If you are using the `gitlab-ssl` file you need to have valid SSL certificates placed where the nginx config says. The message is pretty clear I think.

```
No such file or directory:fopen('/etc/nginx/ssl/gitlab.crt')
```

**Comment by tmacjx** [comment]
@axilleas  
thanks a lot.Have solved.
