### ISSUE TITLE
Tiny error in "Add EPEL repository" chapter of centos recipe

### ISSUE THREAD

**Issue by 2hf** [gitlabhq/gitlab-recipes#279]
When I ran this command
```
wget -O /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6 https://www.fedoraproject.org/static/0608B895.txt
```
I got this Error:
```
ERROR: certificate common name “*.fedoraproject.org” doesn’t match requested host name “getfedora.org”.
To connect to getfedora.org insecurely, use ‘--no-check-certificate’.
```
After adding '--no-check-certificate', it was all good.

So I wonder if this recipe needs to be updated or that's just about my environment?:sweat_smile:

**Comment by axilleas** [comment]
No, it's true because the URL has changed to https://getfedora.org/static/0608B895.txt :)

No need to add `--no-check-certificate` just use the new location.

**Comment by 2hf** [comment]
Oh, i see. Thanks a lot. :ok_hand:
