### ISSUE TITLE
Omnibus GitLab and Plesk 17 onyx using SSL

### ISSUE THREAD

**Issue by KuGelFaaaNg** [gitlabhq/gitlab-recipes#300]
Hello, 

I really hope I am right here and somebody can help me. 

I try since few days to run gitlab on my server with a subdomain, administrated in plesk and a letsencrypt SSL certificate. 

I did try nearly every tutorial or forum thread I can find about this issue. But nothing solved my problem. 

My SSL certificate works finde, I can browse my subdomain and I can open static files. e.g. "http://subdomain.domain.tld/404.html" or "http://subdomain.domain.tld/deploy.html"

When I try to open a file, what not exists, like "http://subdomain.domain.tld/somename.html" I get  page with this text: You need to sign in or sign up before continuing.

When I just want to open the site "http://subdomain.domain.tld/" I get Error "403 Forbidden - nginx".

When I open the sign_up link "https://subdomain.domain.tld/users/sign_in" I can see the login. 

When I create a new user, or try to submit the login form I became a gitlab error page with error "422 The change you requested was rejected."

I created already a root password, I had the error that I was able to create it, but when I logged in, i became HTTP Error 404. I've really tried a lot. 

I have already described it in several forums. Nobody could help me so far. I'm not a good administrator either, so I find these things hard for me.

https://forum.gitlab.com/t/omnibus-gitlab-and-plesk-17-onyx-using-ssl/6214
http://stackoverflow.com/questions/42155092/omnibus-gitlab-and-plesk-17-onyx-using-lets-encrypt-free-ssl-tls-certificates

My current config: 
Additional nginx directives in Plesk: 

```
location ~ / {
	# for omnibus installation
	root /opt/gitlab/embedded/service/gitlab-rails/public;
	autoindex on;
	try_files $uri $uri/index.html $uri.html @gitlab;
}

location @gitlab {
	gzip off;
	proxy_http_version 1.1;
	autoindex on;

	proxy_read_timeout      300;
	proxy_connect_timeout   300;
	proxy_redirect          off;

	proxy_set_header    Host                $http_host;
	proxy_set_header    X-Real-IP           $remote_addr;
	proxy_set_header    X-Forwarded-For     $proxy_add_x_forwarded_for;
	proxy_set_header    X-Forwarded-Proto   http;
	proxy_set_header    X-Frame-Options     SAMEORIGIN;

	proxy_pass http://gitlab;
}
```

gitlab.conf: 

```
upstream gitlab {
    # for omnibus installation
    server unix:/var/opt/gitlab/gitlab-rails/sockets/gitlab.socket;
}
```

gitlab.rb:

```
external_url 'https://subdomain.domain.tld'
web_server['external_users'] = ['Web hosting Access user of domain in plesk']
nginx['enable'] = false
ci_nginx['enable'] = false
nginx['redirect_http_to_https'] = true

nginx['ssl_certificate'] = "/etc/gitlab/ssl/symlinkToMyCertificate.crt"
nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/symlinkToMyKey.key"`
```

I am grateful for any help. Thank you

**Comment by KuGelFaaaNg** [comment]
I tried  "gitlab-ctl cleanse" and  "gitlab-ctl reconfigure", now I was able to create a new admin password and log in again. But still got only 404 when i am logged in.

**Comment by axilleas** [comment]
@KuGelFaaaNg have you tried this http://www.nullalo.com/en/install-and-configure-gitlab-with-plesk-12-on-centos-6/?

**Comment by axilleas** [comment]
Let's continue the discussion in the forum.
