### ISSUE TITLE
Can you provide a GitLab/Gitaly startup service for systemd?

### ISSUE THREAD

**Issue by aihua** [gitlabhq/gitlab-recipes#305]
Gitaly (introduced in GitLab 9.0) is a service that provides high-level RPC access to Git repositories. As of GitLab 9.3 it is still an optional component with limited scope.

Can  you (@axilleas, @randx, @samrocketman, @arif-ali)  provide a Gitaly startup service for systemd?

**Comment by axilleas** [comment]
@aihua let's track this in https://gitlab.com/gitlab-org/gitlab-recipes/issues/64. I opened an MR to try out https://gitlab.com/gitlab-org/gitlab-recipes/merge_requests/63
